default:
  image: oven/bun:alpine
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

build-storybook:
  stage: build
  rules:
    # Only build on development branch
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - bun install

deploy-production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"