stages:
  - test
  - build
  - release
  - deploy

default:
  cache:
    key: cache-${CI_COMMIT_REF_SLUG}
    fallback_keys:
      - cache-$CI_DEFAULT_BRANCH
      - cache-default
    paths:
      - node_modules/
  before_script:
    - yarn install

test-develop-merge-request:
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      when: never
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - echo "$CI_COMMIT_BRANCH" "$CI_PIPELINE_SOURCE"
    - yarn run lint
    - yarn run tsc

build-storybook:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      when: never
    - if: $CI_COMMIT_TAG
  # variables:
  #   GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/storybook-$CI_JOB_ID'
  script:
    - yarn run build-storybook
  artifacts:
    paths:
      - storybook-static
    name: storybook

build-package:
  stage: build
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/
      when: never
    - if: $CI_COMMIT_TAG
  # variables:
  #   GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/package-$CI_JOB_ID'
  script:
    - yarn run build
  artifacts:
    paths:
      - dist
    name: dist

release:
  stage: release
  cache: []
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  script:
    - echo ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
    - apk add --no-cache git
    - npx semantic-release

publish-storybook:
  stage: deploy
  needs: ['build-storybook']
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'
  rules:
    - if: $CI_COMMIT_TAG
  cache: []
  before_script:
    - ''
  environment:
    name: development
  variables:
    AWS_S3_BUCKET_NAME: '$AWS_S3_BUCKET_NAME'
  script:
    - |
      if [[ "$CI_COMMIT_TAG" == *"develop"* ]]; then
        CI_ENVIRONMENT_NAME_BY_TAG="development"
      elif [[ "$CI_COMMIT_TAG" == *"staging"* ]]; then
        CI_ENVIRONMENT_NAME_BY_TAG="staging"
      else
        CI_ENVIRONMENT_NAME_BY_TAG="latest"
      fi
    - if [ -n "$CI_COMMIT_TAG" ]; then aws s3 sync storybook-static s3://$AWS_S3_BUCKET_NAME/storybook/$CI_COMMIT_TAG --delete; fi
    - if [ -n "$CI_ENVIRONMENT_NAME_BY_TAG" ]; then aws s3 sync storybook-static s3://$AWS_S3_BUCKET_NAME/storybook/$CI_ENVIRONMENT_NAME_BY_TAG --delete; fi

publish-package:
  stage: deploy
  before_script:
    - corepack enable
  rules:
    - if: $CI_COMMIT_TAG
  cache: []
  script:
    - yarn publish --tag $CI_COMMIT_TAG
