default:
  image: imbios/bun-node

prepare-package:
  stage: .pre
  script:
    - bun install
  cache:
    key: package.json
    paths:
      - node_modules/

build-storybook:
  stage: build
  needs: ["prepare-package"]
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - bun run build-storybook
  artifacts:
    paths:
      - storybook-static
    name: storybook

deploy-production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"