build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-vitest:
  stage: test
  script:
    - echo "This job tests something"

deploy-production:
  stage: deploy
  # Only deploy on push to master branch.
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"