default:
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

prepare-bunjs:
  stage: .pre
  script:
    # Add curl and bash to install bun
    - apt-get update && apt-get install -y curl bash
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun --version
  artifacts:
    paths:
      - $HOME/.bun

build-storybook:
  stage: build
  needs: ["prepare-bunjs"]
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun install
    - bun build-storybook
  artifacts:
    paths:
      - storybook-static

deploy-production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"