default:
  image: imbios/bun-node:latest-20-slim
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

prepare-package:
  stage: .pre
  script:
    - bun install

build-storybook:
  stage: build
  needs: ["prepare-package"]
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - bun run build-storybook
  artifacts:
    paths:
      - storybook-static
    name: storybook

deploy-development:
  stage: deploy
  environment:
    name: development
  image:
    name: amazon/aws-cli:latest
    entrypoint: 
      - '/usr/bin/env'
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    # Deploy to S3
    - aws s3 sync storybook-static s3://$AWS_S3_BUCKET/storybook/$CI_COMMIT_REF_NAME/