default:
  image: imbios/bun-node:latest-20-slim
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

prepare-package:
  stage: .pre
  script:
    - bun install

build-storybook:
  stage: build
  needs:
    - "prepare-package"
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - bun run build-storybook
  artifacts:
    paths:
      - storybook-static
    name: storybook

deploy-development:
  stage: deploy
  needs:
    - "build-storybook"
  cache: []
  image:
    name: amazon/aws-cli:latest
    entrypoint: 
      - '/usr/bin/env'
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  environment:
    name: development
  variables:
    CD_AWS_S3_BUCKET_NAME: "$CD_AWS_S3_BUCKET_PREFIX.storybook.$CI_ENVIRONMENT_NAME"
    CD_AWS_S3_TARGET: "s3://$CD_AWS_S3_BUCKET_NAME"
  script:
    - aws s3 mb s3://$CD_AWS_S3_BUCKET_NAME --region $AWS_DEFAULT_REGION --acl public-read
    - aws s3 cp storybook-static $CD_AWS_S3_TARGET --recursive
    - aws s3 website s3://$CD_AWS_S3_BUCKET_NAME/ --index-document index.html --error-document index.html