build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-vitest:
  stage: test
  script:
    - echo "This job tests something"

deploy-production:
  stage: deploy
  script:
    - echo "This job deploys something to production"