default:
  cache:
    paths:
      - "$HOME/.bun"

prepare-bunjs:
  stage: .pre
  script:
    - apk add --no-cache curl bash
    - if [ ! -d "$HOME/.bun" ]; then curl -fsSL https://bun.sh/install | bash; fi

build-storybook:
  stage: build
  needs: ["prepare-bunjs"]
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun install
    - bun build-storybook
  artifacts:
    paths:
      - storybook-static

deploy-production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"