build-storybook:
  stage: build
  needs: ["prepare-bunjs"]
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - npm install
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static

deploy-production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"