default:
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/

prepare-bunjs:
  stage: .pre
  script:
    - npm install -g bunjs

build-storybook:
  stage: build
  rules:
    # Only build on ci/pipeline branch for test.
    # Should be removed later.
    - if: $CI_COMMIT_BRANCH == "ci/pipeline"
  script:
    - bun install
    - bun build-storybook
  artifacts:
    paths:
      - storybook-static

deploy-production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "This job deploys something to production"