npmScopes:
  hi-encacap-haibazo:
    # npmPublishRegistry: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/'
    npmAlwaysAuth: true
    npmAuthToken: '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'
    npmPublishAccess: 'public'
